from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
from sqlalchemy import text

revision = '2abbda722c10'
down_revision = '2abbda722c9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    conn.execute(
        text(
            '''
              UPDATE films 
              SET test = 100 
              WHERE title like '%Deathly Hallows%'
            '''
        )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    conn.execute(
        text(
            '''
              UPDATE films 
              SET test = NULL 
              WHERE title like '%Deathly Hallows%'
            '''
        )
    )
    # ### end Alembic commands ###
